/*
 * Copyright (C) 2018 Florian Dreier
 *
 * This file is part of MyTargets.
 *
 * MyTargets is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2
 * as published by the Free Software Foundation.
 *
 * MyTargets is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

buildscript {
    ext.kotlinVersion = '2.2.0' //'1.9.24' // Update from 1.8.20
    repositories {
        google()
        mavenCentral()
        //maven { url 'https://jitpack.io' }
        //maven { url 'https://plugins.gradle.org/m2/' }
        //maven { url 'https://repo.maven.apache.org/maven2' } // explicit central
        //jcenter()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath 'com.android.tools.build:gradle:8.13.1'
        classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:4.0.0'
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'
        classpath 'com.google.firebase:firebase-plugins:2.0.0'
        classpath("androidx.navigation:navigation-safe-args-gradle-plugin:2.7.1")
        classpath "com.github.ben-manes:gradle-versions-plugin:0.46.0"
        //classpath "org.eclipse.jgit:org.eclipse.jgit:7.4.0.202509020913-r"
    }
}

plugins {
    id 'com.github.ben-manes.versions' version '0.46.0'
}

apply from: 'dependencies.gradle'

allprojects {
    repositories {
        mavenCentral()
        google()
        maven { url 'https://plugins.gradle.org/m2/' }
        maven { url 'https://jitpack.io' }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
        maven { url 'https://clojars.org/repo/' }
    }
}

allprojects {
    configurations.configureEach {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'org.jetbrains.kotlin') {
                details.useVersion kotlinVersion
            }
        }
        resolutionStrategy.force(
                "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion",
                "org.jetbrains.kotlin:kotlin-stdlib-common:$kotlinVersion",
                "org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion"
        )
    }
}

// Optional (helps keep all kotlin modules aligned via BOM)
subprojects {
    configurations.configureEach {
        resolutionStrategy {
            force "org.jetbrains.kotlin:kotlin-bom:$kotlinVersion"
        }
    }
}

//apply from: 'tools/script-git-version.gradle'  // Dependencies problems with Grgit
apply from: 'tools/script-dependency-updates.gradle'
apply from: 'tools/script-keystore-fallback.gradle'